version: '3'

services:
  drupal:
    image: drupal
    ports:
      - "8080:80"
    environment:
      - DRUPAL_DATABASE_HOST=mysql
      - DRUPAL_DATABASE_NAME=drupal
      - DRUPAL_DATABASE_USER=root
      - DRUPAL_DATABASE_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - drupal_data:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  drupal_data:
  mysql_data:
