Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Everything is good"
  config.vm.synced_folder "/Users/Kostia/vagrant/data/", "/vagrant_data"

#vm1 congifuration file
  config.vm.define "vm1" do |vm1|
  vm1.vm.box = "bento/ubuntu-22.04"
  vm1.vm.hostname = "vm1"
  vm1.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.1.188"
  vm1.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "2048"
  end
  vm1.vm.provision "shell", inline: <<-SHELL
    echo vm1 - created
     
    #UFW & Ports allowing
    sudo ufw --force enable
    #SSH
    sudo ufw allow 22
    #MySQL
    sudo ufw allow 3306
    #Prometheus
    sudo ufw allow 9100
    #Prometheus MySQLExporter
    sudo ufw allow 9104
    
    #Mysql install
    sudo apt-get update
    sudo apt-get install -y mysql-server
    sudo systemctl start mysql
    sudo systemctl enable mysql
    sudo mysql -e "CREATE DATABASE IF NOT EXISTS Shop;"

    #Prometheus install
    wget https://github.com/prometheus/prometheus/releases/download/v2.37.6/prometheus-2.37.6.linux-amd64.tar.gz
    tar xvfz prometheus-2.37.6.linux-amd64.tar.gz
    sudo mkdir /etc/prometheus /var/lib/prometheus
    sudo mv prometheus /usr/local/bin/
    sudo mv prometheus promtool /usr/local/bin
    sudo mv prometheus.yml /etc/prometheus/prometheus.yml
    sudo mv consoles/ console_libraries/ /etc/prometheus/
    sudo useradd -rs /bin/false prometheus
    sudo chown -R prometheus:prometheus /etc/prometheus /var/lib/prometheus

    #Prometheus MySQL Exporter Installation
    wget https://github.com/prometheus/mysqld_exporter/releases/download/v0.15.1/mysqld_exporter-0.15.1.linux-amd64.tar.gz
    sudo tar xvzf mysqld_exporter-0.15.1.linux-amd64.tar.gz
    sudo mv mysqld_exporter-0.15.1.linux-amd64/mysqld_exporter /usr/local/bin/
    sudo useradd -rs /bin/false mysqlexpr

    
    # Drop the user if it exists, create a new user, grant privileges, and then apply the changes
    sudo mysql -e "DROP USER IF EXISTS 'exporter'@'localhost';"
    sudo mysql -e "CREATE USER 'exporter'@'localhost' IDENTIFIED BY '1722';"
    sudo mysql -e "GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'localhost';"
    sudo mysql -e "FLUSH PRIVILEGES;"


    #Account storage file adding
    sudo mkdir /etc/mysqlexpr/
    sudo mkdir /home/mysqlexpr/
    sudo cp /vagrant_data/vm1/.my.cnf /home/mysqlexpr/.my.cnf
    


    #Node Exporter installation  
    wget https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
    sudo tar xvfz node_exporter-1.5.0.linux-amd64.tar.gz
    sudo mv node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin
    sudo useradd -rs /bin/false nodeusr


    # Copy .service files from /vagrant_data/vm1 to /etc/systemd/system/
    sudo cp /vagrant_data/vm1/*.service /etc/systemd/system/

    #Launch
    sudo systemctl daemon-reload
    sudo systemctl start mysqld_exporter
    sudo systemctl enable mysqld_exporter
    sudo systemctl start node_exporter
    sudo systemctl enable node_exporter

  SHELL
  end

  config.vm.define "vm2" do |vm2|
  vm2.vm.box = "bento/ubuntu-22.04"
  vm2.vm.hostname = "vm2"
  vm2.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.1.159"
  vm2.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "2048"
  end
  vm2.vm.provision "shell", inline: <<-SHELL
  #UFW & Ports allowing
  sudo ufw --force enable
  #SSH
  sudo ufw allow 22
  #Prometheus
  sudo ufw allow 9090
  #Grafana
  sudo ufw allow 3000
  #AlertManager
  sudo ufw allow 9093

    echo vm2 - created
    apt-get update
    sudo apt-get install ntp
    sudo systemctl enable ntp
    sudo systemctl start ntp

    #Grafana installation
    sudo apt-get install -y software-properties-common
    sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
    wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -
    sudo apt-get update
    sudo apt-get install grafana
    sudo systemctl start grafana-server
    sudo systemctl enable grafana-server

    #Prometheus installation
    wget https://github.com/prometheus/prometheus/releases/download/v2.37.6/prometheus-2.37.6.linux-amd64.tar.gz
    tar xvfz prometheus-2.37.6.linux-amd64.tar.gz

    #Replacement of Prometheus files
    sudo mkdir -p /etc/prometheus /var/lib/prometheus
    sudo mv prometheus-2.37.6.linux-amd64/prometheus /usr/local/bin/
    sudo mv prometheus-2.37.6.linux-amd64/promtool /usr/local/bin/
    sudo mv prometheus-2.37.6.linux-amd64/prometheus.yml /etc/prometheus/
    sudo mv prometheus-2.37.6.linux-amd64/consoles/ /etc/prometheus/
    sudo mv prometheus-2.37.6.linux-amd64/console_libraries/ /etc/prometheus/
    
    #Prometheus user adding
    sudo useradd -rs /bin/false prometheus
    sudo chown -R prometheus:prometheus /etc/prometheus /var/lib/prometheus

    #Grafana Repository Adding
    sudo apt-get install -y apt-transport-https software-properties-common
    sudo wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key
    echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | sudo tee -a /etc/apt/sources.list.d/grafana.list

    #Package update & Grafana Install
    sudo apt-get update
    sudo apt-get install -y grafana  

    #AlertManager Installation
    wget https://github.com/prometheus/alertmanager/releases/download/v0.26.0/alertmanager-0.26.0.linux-amd64.tar.gz
    tar -xvzf alertmanager-0.26.0.linux-amd64.tar.gz
    sudo mv alertmanager-0.26.0.linux-amd64/alertmanager /usr/local/bin
    sudo mkdir /etc/alertmanager/ 

    #AlertManager User Adding
    sudo useradd --no-create-home --shell /bin/false alertmanager
    sudo mkdir -p /var/lib/alertmanager/
  
    # Copy .service and .yml files from /vagrant_data/vm2 to appropriate locations
    sudo cp /vagrant_data/vm2/grafana.service /etc/systemd/system/grafana.service
    sudo cp /vagrant_data/vm2/alertmanager.service /etc/systemd/system/
    sudo cp /vagrant_data/vm2/prometheus.service /etc/systemd/system/
    sudo cp /vagrant_data/vm2/alert.rules.yml /etc/prometheus/
    sudo cp /vagrant_data/vm2/prometheus.yml /etc/prometheus/
    sudo cp /vagrant_data/vm2/alertmanager.yml /etc/alertmanager/

    # Make sure Alertmanager owns the configuration file
    sudo chown -R alertmanager:alertmanager /etc/alertmanager
    sudo chown alertmanager:alertmanager /var/lib/alertmanager/
    sudo chown alertmanager:alertmanager /usr/local/bin/alertmanager
    sudo chmod 755 /var/lib/alertmanager/

    # Reload systemd and start services
    sudo systemctl daemon-reload
    sudo systemctl start prometheus
    sudo systemctl enable prometheus
    sudo systemctl start alertmanager
    sudo systemctl enable alertmanager
    sudo systemctl start grafana-server
    sudo systemctl enable grafana-server

  SHELL
  end
end

